name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build shell & test binaries
        run: make all tests/unit/test_fuzzy tests/unit/test_alias

      - name: Run C unit test suite
        run: make test-unit

      - name: Run integration test suite
        run: make test
